ID=1     : size=20989     : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.osapi compute.wsgi.server <:*:> - -] <:IP:> <:*:> <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=2     : size=4373      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO <:*:> <:*:> - - - - -] <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=5     : size=3824      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> <:*:> nova.virt.libvirt.imagecache [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] <:*:> base <:*:> /var/lib/nova/instances/ base/<:SEQ:>
ID=21    : size=3336      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.claims <:*:> - -] [instance: <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=16    : size=2224      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=4     : size=2149      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] image <:DURATION:>d71-34c5-4fbb-86c4-40623fbe45b4 at (/var/lib/nova/instances/ base/<:SEQ:>): in use: on this node <:NUM:> local, <:NUM:> on other nodes sharing this instance storage
ID=13    : size=1936      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server <:*:> - - - - -] <:IP:>,<:IP:> "GET <:*:> <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=14    : size=1385      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server [-] <:IP:>,<:IP:> "GET <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=15    : size=1121      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server [-] <:IP:>,<:IP:> "GET <:*:> <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=23    : size=1116      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server <:*:> - - - - -] <:IP:>,<:IP:> "GET <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=7     : size=1112      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.driver [-] [instance: <:*:> Instance <:*:> successfully.
ID=8     : size=1112      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager <:*:> - -] [instance: <:*:> Took <:NUM:>.<:NUM:> seconds to <:*:> the instance on the hypervisor.
ID=17    : size=1112      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.driver <:*:> - -] [instance: <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=3     : size=1059      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [req-3ea4052c-<:DURATION:>-4b64-9e<:DURATION:>-<:DURATION:>64c<:DURATION:>94ab - - - - -] [instance: <:*:> During sync power state the instance has a pending task (spawning). Skip.
ID=12    : size=933       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO <:*:> <:*:> <:*:> - - - <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=10    : size=756       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.resource tracker [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=6     : size=556       : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.api.openstack.compute.server external events <:*:> - -] Creating event <:*:> for instance <:*:>
ID=9     : size=556       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager <:*:> - -] [instance: <:*:> Took <:NUM:>.<:NUM:> seconds to build instance.
ID=18    : size=556       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager <:*:> - -] [instance: <:*:> Took <:NUM:>.<:NUM:> seconds to deallocate network for instance.
ID=19    : size=556       : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.api.openstack.wsgi <:*:> - -] HTTP exception thrown: No instances found for any event
ID=20    : size=556       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.claims <:*:> - -] [instance: <:*:> Attempting claim: memory <:NUM:> MB, disk <:NUM:> GB, vcpus <:NUM:> CPU
ID=11    : size=378       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.resource tracker [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us phys ram=64172MB used <:*:> phys disk=15GB used <:*:> total vcpus=<:NUM:> used vcpus=<:NUM:> pci stats=[]
ID=25    : size=283       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Base or swap file too young to remove: /var/lib/nova/instances/ base/<:SEQ:>
ID=27    : size=109       : nova-scheduler.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.scheduler.host manager <:*:> - - - - -] The instance sync for host 'cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us' did not match. Re-created its InstanceList.
ID=22    : size=80        : nova-scheduler.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.scheduler.host manager <:*:> - - - - -] Successfully synced instances from host 'cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us'.
ID=26    : size=77        : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.osapi compute.wsgi.server <:*:> - -] <:IP:> "GET /v2/<:SEQ:>/servers/detail?all <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=29    : size=18        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [-] [instance: <:*:> During sync power state the instance has a pending task <:*:> Skip.
ID=28    : size=14        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> WARNING nova.compute.manager [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] While synchronizing instance power states, found <:NUM:> instances in the database and <:NUM:> instances on the hypervisor.
ID=24    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Running instance usage audit for host cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us from <:DATE:> <:TIME:> to <:DATE:> <:TIME:>. <:NUM:> instances.
ID=35    : size=5         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=33    : size=4         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=34    : size=4         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task <:*:> <:*:>
ID=32    : size=3         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task <:*:> <:*:> <:*:> <:*:> <:*:>
ID=30    : size=2         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> WARNING nova.virt.libvirt.driver [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] couldn't obtain the vcpu count from domain id: <:*:> exception: Requested operation is not valid: cpu affinity is not supported
ID=31    : size=1         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Error during ComputeManager. run image cache manager pass
ID=36    : size=1         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task File "/usr/lib/python2.<:NUM:>/dist-packages/nova/virt/libvirt/imagecache.py", line <:NUM:>, in update
ID=37    : size=1         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task File "/usr/lib/python2.<:NUM:>/dist-packages/nova/virt/libvirt/utils.py", line <:NUM:>, in get disk backing file
ID=38    : size=1         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task InvalidDiskInfo: Disk info file is invalid: qemu-img failed to execute on /var/lib/nova/instances/16797a0f-32fb-494c-8f36-38588148c<:DURATION:>/disk : Unexpected error while running command.
ID=39    : size=1         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task Command: /usr/bin/python -m oslo concurrency.prlimit --as=<:NUM:> --cpu=<:NUM:> -- env LC ALL=C LANG=C qemu-img info /var/lib/nova/instances/16797a0f-32fb-494c-8f36-38588148c<:DURATION:>/disk
ID=40    : size=1         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task Exit code: <:NUM:>
ID=41    : size=1         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task Stderr: u"qemu-img: Could not open '/var/lib/nova/instances/16797a0f-32fb-494c-8f36-38588148c<:DURATION:>/disk': Could not open '/var/lib/nova/instances/16797a0f-32fb-494c-8f36-38588148c<:DURATION:>/disk': No such file or directory\n"
ID=42    : size=1         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task
ID=43    : size=1         : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR keystonemiddleware.auth token [req-1cc<:DURATION:>50c-25a2-46b0-a668-<:SEQ:>- - -] Bad response code while validating token: <:NUM:>
ID=44    : size=1         : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> WARNING keystonemiddleware.auth token [req-1cc<:DURATION:>50c-25a2-46b0-a668-<:SEQ:>- - -] Identity response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML <:NUM:>.<:NUM:>//EN">
ID=45    : size=1         : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> CRITICAL keystonemiddleware.auth token [req-1cc<:DURATION:>50c-25a2-46b0-a668-<:SEQ:>- - -] Unable to validate token: Failed to fetch token data from identity server
