ID=4     : size=49485     : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.osapi compute.wsgi.server <:*:> - -] <:IP:> <:*:> <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=10    : size=10327     : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO <:*:> <:*:> - - - - -] <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=2     : size=8972      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> <:*:> nova.virt.libvirt.imagecache [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] <:*:> base <:*:> /var/lib/nova/instances/ base/<:SEQ:>
ID=6     : size=7878      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.claims <:*:> - -] [instance: <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=7     : size=5252      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=11    : size=5077      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] image <:DURATION:>d71-34c5-4fbb-86c4-40623fbe45b4 at (/var/lib/nova/instances/ base/<:SEQ:>): in use: on this node <:NUM:> local, <:NUM:> on other nodes sharing this instance storage
ID=17    : size=4489      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server <:*:> - - - - -] <:IP:>,<:IP:> "GET <:*:> <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=46    : size=4053      : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO <:*:> <:*:> - - - - -] <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=47    : size=4051      : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] image <:DURATION:>d71-34c5-4fbb-86c4-40623fbe45b4 at (/var/lib/nova/instances/ base/<:SEQ:>): in use: on this node <:NUM:> local, <:NUM:> on other nodes sharing this instance storage
ID=48    : size=4051      : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Active base files: /var/lib/nova/instances/ base/<:SEQ:>
ID=20    : size=3069      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server [-] <:IP:>,<:IP:> "GET <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=19    : size=2757      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server [-] <:IP:>,<:IP:> "GET <:*:> <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=14    : size=2624      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.driver [-] [instance: <:*:> Instance <:*:> successfully.
ID=15    : size=2624      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager <:*:> - -] [instance: <:*:> Took <:NUM:>.<:NUM:> seconds to <:*:> the instance on the hypervisor.
ID=21    : size=2624      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.driver <:*:> - -] [instance: <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=18    : size=2616      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server <:*:> - - - - -] <:IP:>,<:IP:> "GET <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=12    : size=2541      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [req-3ea4052c-<:DURATION:>-4b64-9e<:DURATION:>-<:DURATION:>64c<:DURATION:>94ab - - - - -] [instance: <:*:> During sync power state the instance has a pending task (spawning). Skip.
ID=3     : size=2207      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO <:*:> <:*:> <:*:> - - - <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=8     : size=1788      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.resource tracker [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=1     : size=1313      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager <:*:> - -] [instance: <:*:> Took <:NUM:>.<:NUM:> seconds to deallocate network for instance.
ID=5     : size=1313      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.claims <:*:> - -] [instance: <:*:> Attempting claim: memory <:NUM:> MB, disk <:NUM:> GB, vcpus <:NUM:> CPU
ID=13    : size=1312      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.api.openstack.compute.server external events <:*:> - -] Creating event <:*:> for instance <:*:>
ID=16    : size=1312      : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager <:*:> - -] [instance: <:*:> Took <:NUM:>.<:NUM:> seconds to build instance.
ID=22    : size=1312      : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.api.openstack.wsgi <:*:> - -] HTTP exception thrown: No instances found for any event
ID=9     : size=894       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.resource tracker [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us phys ram=64172MB used <:*:> phys disk=15GB used <:*:> total vcpus=<:NUM:> used vcpus=<:NUM:> pci stats=[]
ID=55    : size=664       : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.resource tracker [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=24    : size=638       : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Base or swap file too young to remove: /var/lib/nova/instances/ base/<:SEQ:>
ID=56    : size=332       : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.resource tracker [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us phys ram=64172MB used ram=2560MB phys disk=15GB used disk=20GB total vcpus=<:NUM:> used vcpus=<:NUM:> pci stats=[]
ID=57    : size=332       : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.resource tracker [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Compute service record updated for cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us:cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us
ID=26    : size=226       : nova-scheduler.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.scheduler.host manager <:*:> - - - - -] The instance sync for host 'cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us' did not match. Re-created its InstanceList.
ID=23    : size=219       : nova-scheduler.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.scheduler.host manager <:*:> - - - - -] Successfully synced instances from host 'cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us'.
ID=25    : size=181       : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.osapi compute.wsgi.server <:*:> - -] <:IP:> "GET /v2/<:SEQ:>/servers/detail?all <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=63    : size=165       : nova-scheduler.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.scheduler.host manager <:*:> - - - - -] Successfully synced instances from host 'cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us'.
ID=60    : size=67        : nova-api.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.osapi compute.wsgi.server <:*:> - -] <:IP:> "GET /v2/<:SEQ:>/servers/detail?all <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=29    : size=47        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [-] [instance: <:*:> During sync power state the instance has a pending task <:*:> Skip.
ID=34    : size=35        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=32    : size=28        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:> <:*:>
ID=33    : size=28        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task <:*:> <:*:>
ID=28    : size=27        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> WARNING nova.compute.manager [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] While synchronizing instance power states, found <:NUM:> instances in the database and <:NUM:> instances on the hypervisor.
ID=31    : size=21        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task <:*:> <:*:> <:*:> <:*:> <:*:>
ID=59    : size=17        : nova-api.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server [-] <:IP:>,<:IP:> "GET <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=27    : size=15        : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Running instance usage audit for host cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us from <:DATE:> <:TIME:> to <:DATE:> <:TIME:>. <:NUM:> instances.
ID=42    : size=9         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> WARNING nova.virt.libvirt.driver [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] couldn't obtain the vcpu count from domain id: <:*:> exception: Requested operation is not valid: cpu affinity is not supported
ID=30    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Error during ComputeManager. run image cache manager pass
ID=35    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task File "/usr/lib/python2.<:NUM:>/dist-packages/nova/virt/libvirt/imagecache.py", line <:NUM:>, in update
ID=36    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task File "/usr/lib/python2.<:NUM:>/dist-packages/nova/virt/libvirt/utils.py", line <:NUM:>, in get disk backing file
ID=37    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task InvalidDiskInfo: Disk info file is invalid: qemu-img failed to execute on <:*:> : Unexpected error while running command.
ID=38    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task Command: /usr/bin/python -m oslo concurrency.prlimit --as=<:NUM:> --cpu=<:NUM:> -- env LC ALL=C LANG=C qemu-img info <:*:>
ID=39    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task Exit code: <:NUM:>
ID=40    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task Stderr: u"qemu-img: Could not open <:*:> Could not open <:*:> No such file or directory\n"
ID=41    : size=7         : nova-compute.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR oslo service.periodic task
ID=64    : size=6         : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [req-addc1839-2ed5-<:NUM:>-b57e-5854eb7b8b09 - - - - -] Running instance usage audit for host cp-<:NUM:>.slowvm1.tcloud-pg0.utah.cloudlab.us from <:DATE:> <:TIME:> to <:DATE:> <:TIME:>. <:NUM:> instances.
ID=58    : size=4         : nova-api.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server <:*:> - - - - -] <:IP:>,<:IP:> "GET <:*:> <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=50    : size=3         : nova-api.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.osapi compute.wsgi.server <:*:> - -] <:IP:> <:*:> <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=62    : size=3         : nova-api.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server <:*:> - - - - -] <:IP:>,<:IP:> "GET <:*:> HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=61    : size=2         : nova-api.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.metadata.wsgi.server [-] <:IP:>,<:IP:> "GET <:*:> data.json HTTP/<:NUM:>.<:NUM:>" status: <:NUM:> len: <:NUM:> time: <:NUM:>.<:NUM:>
ID=43    : size=1         : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> ERROR keystonemiddleware.auth token [req-abcdb287-429c-40a5-8e79-<:SEQ:>- - -] Bad response code while validating token: <:NUM:>
ID=44    : size=1         : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> WARNING keystonemiddleware.auth token [req-abcdb287-429c-40a5-8e79-<:SEQ:>- - -] Identity response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML <:NUM:>.<:NUM:>//EN">
ID=45    : size=1         : nova-api.log.<:NUM:>.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> CRITICAL keystonemiddleware.auth token [req-abcdb287-429c-40a5-8e79-<:SEQ:>- - -] Unable to validate token: Failed to fetch token data from identity server
ID=49    : size=1         : nova-api.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.api.openstack.compute.server external events [req-33a38e<:DURATION:>-fbb3-4ea0-a776-<:SEQ:>- - -] Creating event network-vif-plugged:daf5f4cd-6a2f-446c-9bf9-9eb5561aa218 for instance 96c58299-fc8f-4be0-942e-8bcf09431769
ID=51    : size=1         : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.virt.libvirt.driver [-] [instance: 96c58299-fc8f-4be0-942e-8bcf09431769] Instance spawned successfully.
ID=52    : size=1         : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [req-<:DURATION:>8ce09-2e76-4fdb-<:DURATION:>d4-<:SEQ:>- - -] [instance: 96c58299-fc8f-4be0-942e-8bcf09431769] Took <:NUM:>.<:NUM:> seconds to spawn the instance on the hypervisor.
ID=53    : size=1         : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [req-3ea4052c-<:DURATION:>-4b64-9e<:DURATION:>-<:DURATION:>64c<:DURATION:>94ab - - - - -] [instance: 96c58299-fc8f-4be0-942e-8bcf09431769] During sync power state the instance has a pending task (spawning). Skip.
ID=54    : size=1         : nova-compute.log.<:DATE:> <:TIME:> <:DATE:> <:TIME:>.<:NUM:> <:NUM:> INFO nova.compute.manager [req-<:DURATION:>8ce09-2e76-4fdb-<:DURATION:>d4-<:SEQ:>- - -] [instance: 96c58299-fc8f-4be0-942e-8bcf09431769] Took <:NUM:>.<:NUM:> seconds to build instance.
